spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:productsDb
    driverClassName: org.h2.Driver
    password:
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  graphql:
    graphiql:
      enabled: true